### ISSUE TITLE
This assumes the published file belongs to a shot

### ISSUE THREAD

**Issue by kramester** [nimbleheroes/tk-config-nx#68]
this path template needs to be a settiing in the publisher so that it can be set for diff entities (show, seq, asset, etc)
https://github.com/nimbleheroes/tk-config-nx/blob/3efbd9124f44c0e556b2efaba59095e61ba6d520/hooks/tk-multi-publish2/publish_file.py#L587-L590

**Comment by infintropy** [comment]
fixed in #72
